version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  unittests-macos:
    macos:
      xcode: 14.3.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: brew install cmake libomp pytorch
      - run:
          name: Compile and run unit tests
          command: |
            mkdir build
            cd build
            cmake .. -DIGANET_BUILD_UNITTESTS=ON -DTorch_DIR=/usr/local/Cellar/pytorch/2.0.1/share/cmake/Torch -DCMAKE_PREFIX_PATH=/usr/local/Cellar/protobuf@21/21.12/ 
            make
            make test
  unittests-windows:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\IgaNet
    steps:
      - add_ssh_keys:
          fingerprints:
            - "29:67:b0:6b:94:43:da:41:22:00:a2:df:4e:88:f3:dc"
      - checkout:
          path: C:\Users\circleci\project
      - run:
          name: Install dependencies
          command: |
            choco install --no-progress cmake --version 3.24.4 --installargs 'ADD_CMAKE_TO_PATH=System'
            if (-not $?) { throw "Failed to install CMake" }
            choco install --no-progress python3
            if (-not $?) { throw "Failed to install Python" }
      
  
workflows:
  unittests:
    jobs:
      - unittests-windows
